kotlinx.coroutines.test.UncaughtExceptionsBeforeTest: There were uncaught exceptions before the test started. Please avoid this, as such exceptions are also reported in a platform-dependent manner so that they are not lost.
	at app//kotlinx.coroutines.test.TestScopeImpl.enter(TestScope.kt:238)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:309)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:168)
	at app//kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at app//io.ktor.test.dispatcher.TestCommonKt.runTestWithRealTime-8Mi8wO0(TestCommon.kt:37)
	at app//io.ktor.test.dispatcher.TestCommonKt.runTestWithRealTime-8Mi8wO0$default(TestCommon.kt:33)
	at app//io.ktor.server.testing.TestApplicationKt.testApplication(TestApplication.kt:394)
	at app//io.ktor.server.testing.TestApplicationKt.testApplication(TestApplication.kt:355)
	at app//projektor.ApplicationTestCase.projektorTestApplication(ApplicationTestCase.kt:182)
	at app//projektor.notification.github.GitHubPullRequestCommentApplicationTest.should find pull request by commit SHA and add comment to it(GitHubPullRequestCommentApplicationTest.kt:203)
	at java.base@17.0.14/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base@17.0.14/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.14/java.util.ArrayList.forEach(ArrayList.java:1511)
	Suppressed: org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-52)
		at org.jooq_3.19.18.POSTGRES.debug(Unknown Source)
		at app//org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90)
		at app//org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:651)
		at app//org.jooq.impl.AbstractQuery.connection(AbstractQuery.java:388)
		at app//org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:308)
		at app//org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository$recordResultsProcessingError$2.invokeSuspend(ResultsProcessingDatabaseRepository.kt:65)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository$recordResultsProcessingError$2.invoke(ResultsProcessingDatabaseRepository.kt)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository$recordResultsProcessingError$2.invoke(ResultsProcessingDatabaseRepository.kt)
		at app//kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
		at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
		at app//kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository.recordResultsProcessingError(ResultsProcessingDatabaseRepository.kt:59)
		at app//projektor.incomingresults.TestResultsProcessingService.recordResultsProcessingError(TestResultsProcessingService.kt:25)
		at app//projektor.incomingresults.GroupedTestResultsService.doPersistTestResults(GroupedTestResultsService.kt:125)
		at app//projektor.incomingresults.GroupedTestResultsService$persistTestResultsAsync$2.invokeSuspend(GroupedTestResultsService.kt:79)
		at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
		at projektor.incomingresults.GroupedTestResultsService.doPersistTestResults(GroupedTestResultsService.kt:125)
		at projektor.incomingresults.GroupedTestResultsService$persistTestResultsAsync$2.invokeSuspend(GroupedTestResultsService.kt:79)
		Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(1060), "coroutine#1060":StandaloneCoroutine{Cancelled}@2cd8a354, Dispatchers.IO]
	Caused by: org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (HikariPool-52)
		at org.jooq_3.19.18.POSTGRES.debug(Unknown Source)
		at app//org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90)
		at app//org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:651)
		at app//org.jooq.impl.AbstractQuery.connection(AbstractQuery.java:388)
		at app//org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:308)
		at app//org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository$recordResultsProcessingError$2.invokeSuspend(ResultsProcessingDatabaseRepository.kt:65)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository$recordResultsProcessingError$2.invoke(ResultsProcessingDatabaseRepository.kt)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository$recordResultsProcessingError$2.invoke(ResultsProcessingDatabaseRepository.kt)
		at app//kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
		at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
		at app//kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
		at app//projektor.incomingresults.processing.ResultsProcessingDatabaseRepository.recordResultsProcessingError(ResultsProcessingDatabaseRepository.kt:59)
		at app//projektor.incomingresults.TestResultsProcessingService.recordResultsProcessingError(TestResultsProcessingService.kt:25)
		at app//projektor.incomingresults.GroupedTestResultsService.doPersistTestResults(GroupedTestResultsService.kt:125)
		at app//projektor.incomingresults.GroupedTestResultsService$persistTestResultsAsync$2.invokeSuspend(GroupedTestResultsService.kt:79)
		at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
		at app//kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
		at app//kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
		at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-52) has been closed.
		at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:95)
		at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
		... 22 more